### ISSUE TITLE
"database not specified"

### ISSUE THREAD

**Issue by AShabana** [mfou/node-red-contrib-db2#1]
I installed from manage pallet  node-red-contrib-db2
and do simple scenario using input node inject and db2 and output node debug
It give me "database not specified" all time , I put in msg.payload.database name and msg.topic the select sql query 
Did any one face the same ?

**Comment by Jacques44** [comment]
Hello, when you set up the node, you need to give 3 parameters: host, port and database. This third parameter is used by the node to build the connection string which set the property DATABASE= with the value. Did you set this parameter?
